name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Build container image
              run: docker build -t registry.digitalocean.com/bit/php-nginx-base:latest .

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 1200

            - name: Push image to DigitalOcean Container Registry
              run: docker push registry.digitalocean.com/bit/php-nginx-base:latest
